services:
  ketoz:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
      - "4466:4466"
      - "4467:4467"
    restart: on-failure

  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keto
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
